from __future__ import annotations

from fastapi import APIRouter, Depends

from ..deps import get_current_user


router = APIRouter(tags=["skills"])


@router.get("/skills")
def list_skills(_user=Depends(get_current_user)) -> list[dict]:  # noqa: ANN001
    # 先做最小可用：把“工作台里的内置能力”收敛成可配置的内置技能清单
    # 前端将根据这里动态渲染表单/模板，而不是写死在 UI 里。
    return [
        {
            "id": "pipeline_fullstack",
            "name": "AI+通用工具集（全链路 Pipeline）",
            "description": "一键执行视觉、音视频、内容、办公四类能力编排，输出可下载交付物与执行报告。",
            "endpoint": "/api/skills/pipeline/full",
            "default_payload": {
                "deployment_mode": "hybrid",
                "pipelines": ["vision", "media", "content", "office"],
                "input_file_ids": [],
                "vision_payload": {
                    "target_formats": ["webp", "jpg", "png", "avif"],
                    "enhance": True,
                    "resize": {"width": 1600},
                    "crop_presets": ["1:1", "16:9"],
                    "filter_preset": "business",
                    "watermark_text": "AI Toolkit",
                    "watermark_position": "bottom_right",
                    "transparent_background": False,
                },
                "media_payload": {
                    "clip_seconds": 15,
                    "output_resolutions": ["1080", "720"],
                    "target_containers": ["mp4", "hls"],
                    "video_codec": "h264",
                    "subtitle_text": "",
                    "cover_at_second": 1,
                    "trim_silence": True,
                    "merge_input_file_ids": [],
                },
                "content_payload": {
                    "topic": "AI+工具集方案发布",
                    "audience": "小团队与 OPC",
                    "tone": "专业可信",
                    "key_points": ["云边协同", "技能化流程", "可治理交付"],
                    "variants": 3,
                    "languages": ["zh-CN", "en-US"],
                    "rewrite_styles": ["专业版", "亲和版", "冲击版"],
                    "brand_terms": ["AI+通用工具集", "云边协同"],
                    "source_text": "",
                    "review_focus": ["结构层级", "可读性", "品牌一致性"],
                },
                "office_payload": {
                    "project_name": "AI+工具集交付项目",
                    "input_file_ids": [],
                    "tasks": [
                        {"title": "需求确认", "owner": "PM", "due_date": "本周", "priority": "high", "status": "todo"},
                        {"title": "功能联调", "owner": "研发", "due_date": "下周", "priority": "high", "status": "todo"},
                    ],
                    "schedule_items": [
                        {
                            "title": "需求评审",
                            "owner": "PM",
                            "start": "2026-03-18 10:00",
                            "end": "2026-03-18 11:00",
                            "priority": "high",
                            "location": "会议室 A",
                        }
                    ],
                    "meeting_notes": "",
                    "file_conversion_targets": ["txt", "md", "csv", "xlsx", "png", "webp", "mp3", "mp4"],
                    "reminder_hours": [24, 2],
                },
            },
        },
        {
            "id": "pipeline_vision",
            "name": "视觉设计与图像处理 Pipeline",
            "description": "支持文生图、参考图智能重绘/重生成、增强、滤镜与格式转换，适配云端与边缘端输出。",
            "endpoint": "/api/skills/pipeline/vision",
            "default_payload": {
                "deployment_mode": "hybrid",
                "operation": "auto",
                "prompt": "生成一张企业级 AI 工作台封面图，蓝紫科技风、玻璃拟态、干净留白、适合产品首页头图。",
                "input_file_ids": [],
                "size": "1024x1024",
                "quality": "auto",
                "background": "auto",
                "output_format": "png",
                "input_fidelity": "high",
                "edit_scope": "auto",
                "reference_strength": "high",
                "edit_region": {"x": 0.2, "y": 0.18, "width": 0.6, "height": 0.64},
                "target_formats": ["png", "webp", "avif"],
                "enhance": True,
                "resize": {"width": 1600},
                "crop_presets": ["1:1", "16:9"],
                "filter_preset": "business",
                "watermark_text": "JetLinks AI",
                "watermark_position": "bottom_right",
                "transparent_background": False,
            },
        },
        {
            "id": "pipeline_media",
            "name": "视频与音频处理 Pipeline",
            "description": "执行视频剪辑、转码、音频降噪与格式处理，支持云边执行策略切换。",
            "endpoint": "/api/skills/pipeline/media",
            "default_payload": {
                "deployment_mode": "hybrid",
                "input_file_ids": [],
                "clip_seconds": 15,
                "output_resolutions": ["1080", "720"],
                "target_containers": ["mp4", "hls"],
                "video_codec": "h264",
                "subtitle_text": "",
                "cover_at_second": 1,
                "trim_silence": True,
                "merge_input_file_ids": [],
            },
        },
        {
            "id": "pipeline_content",
            "name": "内容创作与写作 Pipeline",
            "description": "自动生成文案包、提案 PPT、报价文档，形成可交付内容资产。",
            "endpoint": "/api/skills/pipeline/content",
            "default_payload": {
                "deployment_mode": "hybrid",
                "topic": "AI+通用工具集升级发布",
                "audience": "小团队与一人公司",
                "tone": "专业、可信、可落地",
                "key_points": ["视觉处理能力", "音视频处理能力", "内容与办公协作能力"],
                "variants": 3,
                "languages": ["zh-CN", "en-US"],
                "rewrite_styles": ["专业版", "亲和版", "冲击版"],
                "brand_terms": ["AI+通用工具集", "云边协同"],
                "source_text": "",
                "review_focus": ["结构层级", "品牌语气", "摘要提炼"],
            },
        },
        {
            "id": "pipeline_office",
            "name": "办公与效率提升 Pipeline",
            "description": "执行日程与任务协作编排，生成项目看板、报价与协作原型交付。",
            "endpoint": "/api/skills/pipeline/office",
            "default_payload": {
                "deployment_mode": "hybrid",
                "project_name": "AI+工具集迭代项目",
                "input_file_ids": [],
                "tasks": [
                    {"title": "里程碑定义", "owner": "PM", "due_date": "本周", "priority": "high", "status": "todo"},
                    {"title": "团队分工", "owner": "交付经理", "due_date": "本周", "priority": "medium", "status": "todo"},
                    {"title": "验收预演", "owner": "QA", "due_date": "下周", "priority": "high", "status": "todo"},
                ],
                "schedule_items": [
                    {
                        "title": "里程碑评审",
                        "owner": "PM",
                        "start": "2026-03-18 10:00",
                        "end": "2026-03-18 11:00",
                        "priority": "high",
                        "location": "线上会议",
                    }
                ],
                "meeting_notes": "",
                "file_conversion_targets": ["txt", "md", "csv", "xlsx", "png", "webp", "mp3", "mp4"],
                "reminder_hours": [24, 2],
            },
        },
        {
            "id": "doc_pptx",
            "name": "PPT 生成（PPTX）",
            "description": "根据模板参数生成 PPTX，并返回下载链接。",
            "endpoint": "/api/docs/ppt",
            "default_payload": {
                "title": "产品方案汇报",
                "style": "template_jetlinks",
                "layout_mode": "auto",
                "template_file_id": "",
                "template_mode": "reuse",
                "template_keep_images": False,
                "template_content_indices": [],
                "slides": [
                    {"title": "目标", "bullets": ["提升转化率", "降低获客成本"]},
                    {"title": "方案", "bullets": ["新增活动页", "A/B 测试", "数据看板"]},
                ],
            },
        },
        {
            "id": "doc_poster_svg",
            "name": "海报大图生成（SVG）",
            "description": "生成可下载的大图海报，适合活动海报、方案长图和社媒封面。",
            "endpoint": "/api/docs/poster",
            "default_payload": {
                "title": "AI 方案发布海报",
                "subtitle": "可下载 · 可归档 · 可继续编辑",
                "bullets": ["支持团队协作", "支持工作区归档", "支持高清长图交付"],
                "footer": "JetLinks AI Workspace",
                "theme": "aurora",
                "width": 1600,
                "height": 2400,
            },
        },
        {
            "id": "doc_quote_docx",
            "name": "报价单（DOCX）",
            "description": "根据模板参数生成报价单 DOCX，并返回下载链接。",
            "endpoint": "/api/docs/quote",
            "default_payload": {
                "seller": "某某科技有限公司",
                "buyer": "某某客户",
                "currency": "CNY",
                "items": [
                    {"name": "需求梳理/PRD", "quantity": 1, "unit_price": 5000, "unit": "项", "note": "含 1 次评审"},
                    {"name": "原型设计", "quantity": 1, "unit_price": 8000, "unit": "项", "note": "含 2 次迭代"},
                ],
                "note": "交付周期：10 个工作日；不含第三方费用。",
            },
        },
        {
            "id": "doc_quote_xlsx",
            "name": "报价单（XLSX）",
            "description": "根据模板参数生成专业样式报价单 XLSX（参考脚本风格），并返回下载链接。",
            "endpoint": "/api/docs/quote-xlsx",
            "default_payload": {
                "seller": "某某科技有限公司",
                "buyer": "某某客户",
                "currency": "CNY",
                "items": [
                    {"name": "需求梳理/PRD", "quantity": 1, "unit_price": 5000, "unit": "项", "note": "含 1 次评审"},
                    {"name": "原型设计", "quantity": 1, "unit_price": 8000, "unit": "项", "note": "含 2 次迭代"},
                ],
                "note": "交付周期：10 个工作日；不含第三方费用。",
            },
        },
        {
            "id": "doc_inspection_docx",
            "name": "报检单/检验单（DOCX）",
            "description": "生成通用“物联网设备报检单/检验单”DOCX 模板，并返回下载链接。",
            "endpoint": "/api/docs/inspection",
            "default_payload": {
                "title": "物联网设备报检单",
                "basic_info": {
                    "report_no": "",
                    "report_date": "",
                    "applicant_unit": "某某科技有限公司 / 质量部",
                    "contact_name": "",
                    "contact_phone": "",
                    "contact_email": "",
                    "project_order_no": "",
                    "inspection_type": "到货报检（IQC）",
                    "inspection_method": "抽检",
                    "sampling_standard": "AQL 1.0 / II",
                    "acceptance_standard": "按规格书/协议",
                },
                "device_info": {
                    "device_name": "温湿度传感器",
                    "model": "TH-100",
                    "category": "传感器",
                    "quantity": "100",
                    "unit": "台",
                    "sn_range": "",
                    "firmware_version": "",
                    "hardware_version": "",
                    "manufacturer": "",
                    "brand": "",
                    "batch": "",
                    "supplier": "",
                    "doc_no": "",
                },
                "network_info": {
                    "communication": "NB-IoT",
                    "carrier_band_power": "",
                    "sim_iccid": "",
                    "mac_imei": "",
                    "security": "TLS",
                    "key_provisioning": "",
                    "power": "电池",
                    "battery": "",
                    "certifications": "CCC/SRRC（如适用）",
                    "materials": "规格书/说明书/出厂检验报告（按需）",
                },
                "inspection_info": {"reference": "规格书/图纸/项目协议（填写版本号）", "environment": "温度 25℃；湿度 50%RH；供电 —"},
                "inspection_items": [
                    {"name": "外观与包装"},
                    {"name": "标识与追溯（铭牌/SN/二维码）"},
                    {"name": "通电自检/启动"},
                    {"name": "传感/采集精度（如适用）"},
                    {"name": "通信注册/入网/连接稳定性"},
                    {"name": "平台对接（MQTT/HTTP/CoAP 等）"},
                    {"name": "远程配置/OTA 升级"},
                    {"name": "告警/事件上报"},
                    {"name": "功耗/续航（如适用）"},
                    {"name": "安全项（TLS/证书/密钥/弱口令）"},
                ],
                "conclusion": {"result": "□合格 □让步接收 □返工/返修 □退货 □待复检"},
                "signatures": {"reporter": "", "inspector": "", "reviewer": "", "date": ""},
                "attachments": [],
            },
        },
        {
            "id": "doc_inspection_xlsx",
            "name": "报检单/检验单（XLSX）",
            "description": "生成通用“物联网设备报检单/检验单”XLSX 模板（更适合表格填写），并返回下载链接。",
            "endpoint": "/api/docs/inspection-xlsx",
            "default_payload": {
                "title": "物联网设备报检单",
                "basic_info": {
                    "report_no": "",
                    "report_date": "",
                    "applicant_unit": "某某科技有限公司 / 质量部",
                    "contact_name": "",
                    "contact_phone": "",
                    "contact_email": "",
                    "project_order_no": "",
                    "inspection_type": "到货报检（IQC）",
                    "inspection_method": "抽检",
                    "sampling_standard": "AQL 1.0 / II",
                    "acceptance_standard": "按规格书/协议",
                },
                "device_info": {
                    "device_name": "温湿度传感器",
                    "model": "TH-100",
                    "category": "传感器",
                    "quantity": "100",
                    "unit": "台",
                    "sn_range": "",
                    "firmware_version": "",
                    "hardware_version": "",
                    "manufacturer": "",
                    "brand": "",
                    "batch": "",
                    "supplier": "",
                    "doc_no": "",
                },
                "network_info": {
                    "communication": "NB-IoT",
                    "carrier_band_power": "",
                    "sim_iccid": "",
                    "mac_imei": "",
                    "security": "TLS",
                    "key_provisioning": "",
                    "power": "电池",
                    "battery": "",
                    "certifications": "CCC/SRRC（如适用）",
                    "materials": "规格书/说明书/出厂检验报告（按需）",
                },
                "inspection_info": {"reference": "规格书/图纸/项目协议（填写版本号）", "environment": "温度 25℃；湿度 50%RH；供电 —"},
                "inspection_items": [
                    {"name": "外观与包装"},
                    {"name": "标识与追溯（铭牌/SN/二维码）"},
                    {"name": "通电自检/启动"},
                    {"name": "传感/采集精度（如适用）"},
                    {"name": "通信注册/入网/连接稳定性"},
                    {"name": "平台对接（MQTT/HTTP/CoAP 等）"},
                    {"name": "远程配置/OTA 升级"},
                    {"name": "告警/事件上报"},
                    {"name": "功耗/续航（如适用）"},
                    {"name": "安全项（TLS/证书/密钥/弱口令）"},
                ],
                "conclusion": {"result": "□合格 □让步接收 □返工/返修 □退货 □待复检"},
                "signatures": {"reporter": "", "inspector": "", "reviewer": "", "date": ""},
                "attachments": [],
            },
        },
        {
            "id": "proto_zip",
            "name": "原型（HTML ZIP）",
            "description": "生成多页 HTML 原型并打包 ZIP，返回下载链接。",
            "endpoint": "/api/prototype/generate",
            "default_payload": {
                "project_name": "智慧社区平台",
                "pages": [
                    {"title": "数据接入管理", "description": "接入源管理、状态监控"},
                    {"title": "告警中心", "description": "告警列表、处理流程"},
                    {"title": "统计分析", "description": "指标与报表"},
                ],
            },
        },
    ]
