from __future__ import annotations

from fastapi import APIRouter, Depends

from ..deps import get_current_user


router = APIRouter(tags=["skills"])


@router.get("/skills")
def list_skills(_user=Depends(get_current_user)) -> list[dict]:  # noqa: ANN001
    # 先做最小可用：把“工作台里的内置能力”收敛成可配置的内置技能清单
    # 前端将根据这里动态渲染表单/模板，而不是写死在 UI 里。
    return [
        {
            "id": "doc_pptx",
            "name": "PPT 生成（PPTX）",
            "description": "根据模板参数生成 PPTX，并返回下载链接。",
            "endpoint": "/api/docs/ppt",
            "default_payload": {
                "title": "产品方案汇报",
                "style": "template_jetlinks",
                "layout_mode": "auto",
                "template_file_id": "",
                "template_mode": "reuse",
                "template_keep_images": False,
                "template_content_indices": [],
                "slides": [
                    {"title": "目标", "bullets": ["提升转化率", "降低获客成本"]},
                    {"title": "方案", "bullets": ["新增活动页", "A/B 测试", "数据看板"]},
                ],
            },
        },
        {
            "id": "doc_quote_docx",
            "name": "报价单（DOCX）",
            "description": "根据模板参数生成报价单 DOCX，并返回下载链接。",
            "endpoint": "/api/docs/quote",
            "default_payload": {
                "seller": "某某科技有限公司",
                "buyer": "某某客户",
                "currency": "CNY",
                "items": [
                    {"name": "需求梳理/PRD", "quantity": 1, "unit_price": 5000, "unit": "项", "note": "含 1 次评审"},
                    {"name": "原型设计", "quantity": 1, "unit_price": 8000, "unit": "项", "note": "含 2 次迭代"},
                ],
                "note": "交付周期：10 个工作日；不含第三方费用。",
            },
        },
        {
            "id": "doc_quote_xlsx",
            "name": "报价单（XLSX）",
            "description": "根据模板参数生成专业样式报价单 XLSX（参考脚本风格），并返回下载链接。",
            "endpoint": "/api/docs/quote-xlsx",
            "default_payload": {
                "seller": "某某科技有限公司",
                "buyer": "某某客户",
                "currency": "CNY",
                "items": [
                    {"name": "需求梳理/PRD", "quantity": 1, "unit_price": 5000, "unit": "项", "note": "含 1 次评审"},
                    {"name": "原型设计", "quantity": 1, "unit_price": 8000, "unit": "项", "note": "含 2 次迭代"},
                ],
                "note": "交付周期：10 个工作日；不含第三方费用。",
            },
        },
        {
            "id": "doc_inspection_docx",
            "name": "报检单/检验单（DOCX）",
            "description": "生成通用“物联网设备报检单/检验单”DOCX 模板，并返回下载链接。",
            "endpoint": "/api/docs/inspection",
            "default_payload": {
                "title": "物联网设备报检单",
                "basic_info": {
                    "report_no": "",
                    "report_date": "",
                    "applicant_unit": "某某科技有限公司 / 质量部",
                    "contact_name": "",
                    "contact_phone": "",
                    "contact_email": "",
                    "project_order_no": "",
                    "inspection_type": "到货报检（IQC）",
                    "inspection_method": "抽检",
                    "sampling_standard": "AQL 1.0 / II",
                    "acceptance_standard": "按规格书/协议",
                },
                "device_info": {
                    "device_name": "温湿度传感器",
                    "model": "TH-100",
                    "category": "传感器",
                    "quantity": "100",
                    "unit": "台",
                    "sn_range": "",
                    "firmware_version": "",
                    "hardware_version": "",
                    "manufacturer": "",
                    "brand": "",
                    "batch": "",
                    "supplier": "",
                    "doc_no": "",
                },
                "network_info": {
                    "communication": "NB-IoT",
                    "carrier_band_power": "",
                    "sim_iccid": "",
                    "mac_imei": "",
                    "security": "TLS",
                    "key_provisioning": "",
                    "power": "电池",
                    "battery": "",
                    "certifications": "CCC/SRRC（如适用）",
                    "materials": "规格书/说明书/出厂检验报告（按需）",
                },
                "inspection_info": {"reference": "规格书/图纸/项目协议（填写版本号）", "environment": "温度 25℃；湿度 50%RH；供电 —"},
                "inspection_items": [
                    {"name": "外观与包装"},
                    {"name": "标识与追溯（铭牌/SN/二维码）"},
                    {"name": "通电自检/启动"},
                    {"name": "传感/采集精度（如适用）"},
                    {"name": "通信注册/入网/连接稳定性"},
                    {"name": "平台对接（MQTT/HTTP/CoAP 等）"},
                    {"name": "远程配置/OTA 升级"},
                    {"name": "告警/事件上报"},
                    {"name": "功耗/续航（如适用）"},
                    {"name": "安全项（TLS/证书/密钥/弱口令）"},
                ],
                "conclusion": {"result": "□合格 □让步接收 □返工/返修 □退货 □待复检"},
                "signatures": {"reporter": "", "inspector": "", "reviewer": "", "date": ""},
                "attachments": [],
            },
        },
        {
            "id": "doc_inspection_xlsx",
            "name": "报检单/检验单（XLSX）",
            "description": "生成通用“物联网设备报检单/检验单”XLSX 模板（更适合表格填写），并返回下载链接。",
            "endpoint": "/api/docs/inspection-xlsx",
            "default_payload": {
                "title": "物联网设备报检单",
                "basic_info": {
                    "report_no": "",
                    "report_date": "",
                    "applicant_unit": "某某科技有限公司 / 质量部",
                    "contact_name": "",
                    "contact_phone": "",
                    "contact_email": "",
                    "project_order_no": "",
                    "inspection_type": "到货报检（IQC）",
                    "inspection_method": "抽检",
                    "sampling_standard": "AQL 1.0 / II",
                    "acceptance_standard": "按规格书/协议",
                },
                "device_info": {
                    "device_name": "温湿度传感器",
                    "model": "TH-100",
                    "category": "传感器",
                    "quantity": "100",
                    "unit": "台",
                    "sn_range": "",
                    "firmware_version": "",
                    "hardware_version": "",
                    "manufacturer": "",
                    "brand": "",
                    "batch": "",
                    "supplier": "",
                    "doc_no": "",
                },
                "network_info": {
                    "communication": "NB-IoT",
                    "carrier_band_power": "",
                    "sim_iccid": "",
                    "mac_imei": "",
                    "security": "TLS",
                    "key_provisioning": "",
                    "power": "电池",
                    "battery": "",
                    "certifications": "CCC/SRRC（如适用）",
                    "materials": "规格书/说明书/出厂检验报告（按需）",
                },
                "inspection_info": {"reference": "规格书/图纸/项目协议（填写版本号）", "environment": "温度 25℃；湿度 50%RH；供电 —"},
                "inspection_items": [
                    {"name": "外观与包装"},
                    {"name": "标识与追溯（铭牌/SN/二维码）"},
                    {"name": "通电自检/启动"},
                    {"name": "传感/采集精度（如适用）"},
                    {"name": "通信注册/入网/连接稳定性"},
                    {"name": "平台对接（MQTT/HTTP/CoAP 等）"},
                    {"name": "远程配置/OTA 升级"},
                    {"name": "告警/事件上报"},
                    {"name": "功耗/续航（如适用）"},
                    {"name": "安全项（TLS/证书/密钥/弱口令）"},
                ],
                "conclusion": {"result": "□合格 □让步接收 □返工/返修 □退货 □待复检"},
                "signatures": {"reporter": "", "inspector": "", "reviewer": "", "date": ""},
                "attachments": [],
            },
        },
        {
            "id": "proto_zip",
            "name": "原型（HTML ZIP）",
            "description": "生成多页 HTML 原型并打包 ZIP，返回下载链接。",
            "endpoint": "/api/prototype/generate",
            "default_payload": {
                "project_name": "智慧社区平台",
                "pages": [
                    {"title": "数据接入管理", "description": "接入源管理、状态监控"},
                    {"title": "告警中心", "description": "告警列表、处理流程"},
                    {"title": "统计分析", "description": "指标与报表"},
                ],
            },
        },
    ]
